name: scs_go
description: SCS GO - Ứng dụng sạc xe điện thông minh
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^13.0.0
  
  # UI Components
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  
  # Location
  geolocator: ^10.1.0
  
  # Supabase
  supabase_flutter: ^2.3.0
  
  # QR Code
  qr_flutter: ^4.1.0
  
  # HTTP Client
  http: ^1.2.0
  
  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/logo.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/logo.jpg"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
